[unstable]
build-std-features = ["compiler-builtins-mem"]
# 告知cargo需要重新编译 core 和 compiler_builtins 这两个crate，其中 compiler_builtins 是 core 的必要依赖。
build-std = ["core", "compiler_builtins"] 

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"